#!/bin/bash
# Script 1: System Identity Report
# Author: Siya Sanjit Sawant Dessai | Course: Open Source Software

# --- Variables ---
STUDENT_NAME="Siya Sanjit Sawant Dessai"
SOFTWARE_CHOICE="Linux Kernel"

# --- System info ---
KERNEL=$(uname -r)
USER_NAME=$(whoami)
UPTIME=$(uptime -p)
DISTRO=$(grep PRETTY_NAME /etc/os-release | cut -d '"' -f 2)
HOME_DIR=$HOME
CURRENT_DATE=$(date +"%A, %B %d, %Y at %T")
LICENSE="GNU General Public License (GPL) version 2"

# --- Display ---
echo "---------------------------------------------------"
echo " Open Source Audit - $SIYA SANJIT SAWANT DESSAI"
echo "---------------------------------------------------"
echo "Distro      : $DISTRO"
echo "Kernel      : $KERNEL"
echo "User        : $USER_NAME"
echo "Home Direct.: $HOME_DIR"
echo "Uptime      : $UPTIME"
echo "Date & Time : $CURRENT_DATE"
echo "---------------------------------------------------"
echo "License     : $LICENSE"
echo "---------------------------------------------------"
